-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

ALTER TABLE "app"."user" ADD COLUMN "profile_version" INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE "app"."user" ADD CONSTRAINT "user_profile_version_nonnegative" CHECK ("profile_version" >= 0);
