-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."standalone_checkout_attempt" (
  "id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "order_v2_id" UUID NOT NULL,
  "retry_key_verifier" VARCHAR(64) NOT NULL,
  "request_verifier" VARCHAR(64) NOT NULL,
  "capability_nonce" VARCHAR(43) NOT NULL,
  "capability_key_version" VARCHAR(16) NOT NULL,
  "capability_verifier" VARCHAR(64) NOT NULL,
  "capability_expires_at" TIMESTAMPTZ NOT NULL,
  "capability_revoked_at" TIMESTAMPTZ,
  "state" VARCHAR(13) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."standalone_checkout_attempt" ADD CONSTRAINT "standalone_checkout_attempt_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."standalone_checkout_attempt" ADD CONSTRAINT "standalone_checkout_attempt_owner_retry_key_verifier_key" UNIQUE ("owner_id", "retry_key_verifier");

ALTER TABLE "app"."standalone_checkout_attempt" ADD CONSTRAINT "standalone_checkout_attempt_order_v2_id_key" UNIQUE ("order_v2_id");

ALTER TABLE "app"."standalone_checkout_attempt" ADD CONSTRAINT "standalone_checkout_attempt_order_owner_key" UNIQUE ("order_v2_id", "owner_id");

ALTER TABLE "app"."standalone_checkout_attempt" ADD CONSTRAINT "standalone_checkout_attempt_owner_fkey" FOREIGN KEY ("owner_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."standalone_checkout_attempt" ADD CONSTRAINT "standalone_checkout_attempt_order_owner_fkey" FOREIGN KEY ("order_v2_id", "owner_id") REFERENCES "app"."order_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "standalone_checkout_attempt_owner_capability_expiry_idx" ON "app"."standalone_checkout_attempt" ("owner_id", "capability_expires_at");

GRANT SELECT, INSERT, UPDATE ON TABLE "app"."standalone_checkout_attempt" TO "qr_runtime";
