-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."totp_credential" (
  "user_id" UUID NOT NULL,
  "encrypted_secret" TEXT NOT NULL,
  "confirmed_at" TIMESTAMPTZ,
  "replay_counter" INTEGER DEFAULT 0 NOT NULL,
  "algorithm" VARCHAR(10) DEFAULT 'SHA1' NOT NULL,
  "digits" INTEGER DEFAULT 6 NOT NULL,
  "step_seconds" INTEGER DEFAULT 30 NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."totp_credential" ADD CONSTRAINT "totp_credential_pkey" PRIMARY KEY ("user_id");

ALTER TABLE "app"."totp_credential" ADD CONSTRAINT "totp_credential_user_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "app"."totp_recovery_code" (
  "id" UUID NOT NULL,
  "credential_id" UUID NOT NULL,
  "code_digest" VARCHAR(64) NOT NULL,
  "consumed_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."totp_recovery_code" ADD CONSTRAINT "totp_recovery_code_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."totp_recovery_code" ADD CONSTRAINT "totp_recovery_code_credential_fkey" FOREIGN KEY ("credential_id") REFERENCES "app"."totp_credential" ("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "totp_recovery_code_credential_id_idx" ON "app"."totp_recovery_code" ("credential_id");

CREATE TABLE "app"."totp_recovery_action" (
  "id" UUID NOT NULL,
  "actor_id" UUID NOT NULL,
  "target_id" UUID NOT NULL,
  "action" VARCHAR(16) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."totp_recovery_action" ADD CONSTRAINT "totp_recovery_action_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."totp_recovery_action" ADD CONSTRAINT "totp_recovery_action_target_fkey" FOREIGN KEY ("target_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "totp_recovery_action_target_id_idx" ON "app"."totp_recovery_action" ("target_id");

CREATE TABLE "app"."mfa_challenge" (
  "id" UUID NOT NULL,
  "user_id" UUID NOT NULL,
  "token_digest" VARCHAR(64) NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "used_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."mfa_challenge" ADD CONSTRAINT "mfa_challenge_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."mfa_challenge" ADD CONSTRAINT "mfa_challenge_token_digest_key" UNIQUE ("token_digest");

ALTER TABLE "app"."mfa_challenge" ADD CONSTRAINT "mfa_challenge_user_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "mfa_challenge_user_created_at_idx" ON "app"."mfa_challenge" ("user_id", "created_at");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."totp_credential" TO "qr_runtime";

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."totp_recovery_code" TO "qr_runtime";

GRANT SELECT, INSERT ON TABLE "app"."totp_recovery_action" TO "qr_runtime";

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."mfa_challenge" TO "qr_runtime";
