-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."system_settings" (
  "id" SMALLINT NOT NULL,
  "default_theme_id" VARCHAR(24),
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."system_settings" ADD CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."system_settings" ADD CONSTRAINT "system_settings_singleton" CHECK ("id" = 1);

ALTER TABLE "app"."system_settings" ADD CONSTRAINT "system_settings_default_theme_id_closed" CHECK ("default_theme_id" IN ('pix-paper', 'cashier-daylight', 'settlement-sand', 'midnight-clearing', 'vault-blue', 'terminal-amber'));

GRANT SELECT, INSERT, UPDATE ON TABLE "app"."system_settings" TO "qr_runtime";
