-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."order_v2" (
  "id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "source" TEXT NOT NULL,
  "payment_link_v2_id" UUID,
  "state" VARCHAR(13),
  "lifecycle_version" INTEGER NOT NULL,
  "amount" TEXT NOT NULL,
  "currency_uuid" UUID NOT NULL,
  "exchange_currency_uuid" UUID NOT NULL,
  "description_pt_br" VARCHAR(160),
  "description_en" VARCHAR(160),
  "checkout_data_policy" VARCHAR(22) NOT NULL,
  "name" VARCHAR(160),
  "email" VARCHAR(254),
  "cpf" VARCHAR(11),
  "street" VARCHAR(160),
  "number" VARCHAR(32),
  "district" VARCHAR(120),
  "city" VARCHAR(120),
  "state_uf" VARCHAR(2),
  "postal_code" VARCHAR(8),
  "country" VARCHAR(2),
  "complement" VARCHAR(160),
  "settled_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."order_v2" ADD CONSTRAINT "order_v2_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."order_v2" ADD CONSTRAINT "order_v2_id_owner_id_key" UNIQUE ("id", "owner_id");

ALTER TABLE "app"."order_v2" ADD CONSTRAINT "order_v2_owner_fkey" FOREIGN KEY ("owner_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_v2" ADD CONSTRAINT "order_v2_link_owner_fkey" FOREIGN KEY ("payment_link_v2_id", "owner_id") REFERENCES "app"."payment_link_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_v2" ADD CONSTRAINT "order_v2_state_closed" CHECK (("state" IS NULL) OR ("state" IN ('CREATED', 'PENDING', 'INDETERMINATE', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'REFUNDED')));

ALTER TABLE "app"."order_v2" ADD CONSTRAINT "order_v2_policy_closed" CHECK ("checkout_data_policy" IN ('NONE', 'NAME_EMAIL', 'EMAIL', 'NAME_EMAIL_CPF', 'NAME_EMAIL_CPF_ADDRESS'));

ALTER TABLE "app"."order_v2" ADD CONSTRAINT "order_v2_lifecycle_version_nonnegative" CHECK ("lifecycle_version" >= 0);

CREATE TABLE "app"."order_v2_line" (
  "order_id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "product_id" UUID NOT NULL,
  "position" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit_price" TEXT NOT NULL
);

ALTER TABLE "app"."order_v2_line" ADD CONSTRAINT "order_v2_line_pkey" PRIMARY KEY ("order_id", "position");

ALTER TABLE "app"."order_v2_line" ADD CONSTRAINT "order_v2_line_order_product_key" UNIQUE ("order_id", "product_id");

ALTER TABLE "app"."order_v2_line" ADD CONSTRAINT "order_v2_line_order_owner_fkey" FOREIGN KEY ("order_id", "owner_id") REFERENCES "app"."order_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_v2_line" ADD CONSTRAINT "order_v2_line_product_owner_fkey" FOREIGN KEY ("product_id", "owner_id") REFERENCES "app"."product" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_v2_line" ADD CONSTRAINT "order_v2_line_position_bounds" CHECK (("position" >= 1) AND ("position" <= 20));

ALTER TABLE "app"."order_v2_line" ADD CONSTRAINT "order_v2_line_quantity_bounds" CHECK (("quantity" >= 1) AND ("quantity" <= 9999));

CREATE TABLE "app"."order_comment_v2" (
  "id" UUID NOT NULL,
  "order_id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "author_id" UUID NOT NULL,
  "body" VARCHAR(2000) NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "edited_at" TIMESTAMPTZ
);

ALTER TABLE "app"."order_comment_v2" ADD CONSTRAINT "order_comment_v2_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."order_comment_v2" ADD CONSTRAINT "order_comment_v2_order_owner_fkey" FOREIGN KEY ("order_id", "owner_id") REFERENCES "app"."order_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_comment_v2" ADD CONSTRAINT "order_comment_v2_author_fkey" FOREIGN KEY ("author_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_comment_v2" ADD CONSTRAINT "order_comment_v2_version_nonnegative" CHECK ("version" >= 0);

CREATE TABLE "app"."order_local_outcome_v2" (
  "id" UUID NOT NULL,
  "order_id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "outcome" VARCHAR(16) NOT NULL,
  "note" VARCHAR(2000),
  "actor_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."order_local_outcome_v2" ADD CONSTRAINT "order_local_outcome_v2_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."order_local_outcome_v2" ADD CONSTRAINT "order_local_outcome_v2_order_owner_fkey" FOREIGN KEY ("order_id", "owner_id") REFERENCES "app"."order_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_local_outcome_v2" ADD CONSTRAINT "order_local_outcome_v2_actor_fkey" FOREIGN KEY ("actor_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."order_local_outcome_v2" ADD CONSTRAINT "order_local_outcome_v2_outcome_closed" CHECK ("outcome" IN ('LOCAL_FINALIZED', 'LOCAL_CANCELLED'));

CREATE TABLE "app"."checkout_attempt_v2" (
  "id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "payment_link_v2_id" UUID NOT NULL,
  "order_v2_id" UUID NOT NULL,
  "retry_key_verifier" VARCHAR(64) NOT NULL,
  "request_verifier" VARCHAR(64) NOT NULL,
  "capability_nonce" VARCHAR(43) NOT NULL,
  "capability_key_version" VARCHAR(16) NOT NULL,
  "capability_verifier" VARCHAR(64) NOT NULL,
  "capability_expires_at" TIMESTAMPTZ NOT NULL,
  "capability_revoked_at" TIMESTAMPTZ,
  "state" VARCHAR(13) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."checkout_attempt_v2" ADD CONSTRAINT "checkout_attempt_v2_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."checkout_attempt_v2" ADD CONSTRAINT "checkout_attempt_v2_link_retry_key_verifier_key" UNIQUE ("payment_link_v2_id", "retry_key_verifier");

ALTER TABLE "app"."checkout_attempt_v2" ADD CONSTRAINT "checkout_attempt_v2_order_v2_id_key" UNIQUE ("order_v2_id");

ALTER TABLE "app"."checkout_attempt_v2" ADD CONSTRAINT "checkout_attempt_v2_order_owner_key" UNIQUE ("order_v2_id", "owner_id");

ALTER TABLE "app"."checkout_attempt_v2" ADD CONSTRAINT "checkout_attempt_v2_owner_fkey" FOREIGN KEY ("owner_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."checkout_attempt_v2" ADD CONSTRAINT "checkout_attempt_v2_link_owner_fkey" FOREIGN KEY ("payment_link_v2_id", "owner_id") REFERENCES "app"."payment_link_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."checkout_attempt_v2" ADD CONSTRAINT "checkout_attempt_v2_order_owner_fkey" FOREIGN KEY ("order_v2_id", "owner_id") REFERENCES "app"."order_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "app"."payment_link_v2_single_use_settlement" (
  "payment_link_v2_id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "order_v2_id" UUID NOT NULL,
  "claimed_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."payment_link_v2_single_use_settlement" ADD CONSTRAINT "payment_link_v2_single_use_settlement_pkey" PRIMARY KEY ("payment_link_v2_id");

ALTER TABLE "app"."payment_link_v2_single_use_settlement" ADD CONSTRAINT "payment_link_v2_single_use_settlement_order_key" UNIQUE ("order_v2_id");

ALTER TABLE "app"."payment_link_v2_single_use_settlement" ADD CONSTRAINT "payment_link_v2_single_use_settlement_link_owner_key" UNIQUE ("payment_link_v2_id", "owner_id");

ALTER TABLE "app"."payment_link_v2_single_use_settlement" ADD CONSTRAINT "payment_link_v2_single_use_settlement_order_owner_key" UNIQUE ("order_v2_id", "owner_id");

ALTER TABLE "app"."payment_link_v2_single_use_settlement" ADD CONSTRAINT "payment_link_v2_single_use_settlement_link_owner_fkey" FOREIGN KEY ("payment_link_v2_id", "owner_id") REFERENCES "app"."payment_link_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."payment_link_v2_single_use_settlement" ADD CONSTRAINT "payment_link_v2_single_use_settlement_order_owner_fkey" FOREIGN KEY ("order_v2_id", "owner_id") REFERENCES "app"."order_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."provider_order" ADD COLUMN "order_v2_id" UUID;

ALTER TABLE "app"."provider_order" ADD CONSTRAINT "provider_order_order_v2_owner_key" UNIQUE ("order_v2_id", "owner_id");

ALTER TABLE "app"."provider_order" ADD CONSTRAINT "provider_order_order_v2_owner_fkey" FOREIGN KEY ("order_v2_id", "owner_id") REFERENCES "app"."order_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "order_v2_owner_created_at_id_idx" ON "app"."order_v2" ("owner_id", "created_at", "id");

CREATE INDEX "order_v2_owner_source_created_at_id_idx" ON "app"."order_v2" ("owner_id", "source", "created_at", "id");

CREATE INDEX "order_v2_owner_state_created_at_id_idx" ON "app"."order_v2" ("owner_id", "state", "created_at", "id");

CREATE INDEX "order_v2_link_created_at_id_idx" ON "app"."order_v2" ("payment_link_v2_id", "created_at", "id");

CREATE INDEX "order_comment_v2_order_created_at_id_idx" ON "app"."order_comment_v2" ("order_id", "created_at", "id");

CREATE INDEX "order_local_outcome_v2_order_created_at_id_idx" ON "app"."order_local_outcome_v2" ("order_id", "created_at", "id");

CREATE INDEX "checkout_attempt_v2_owner_capability_expiry_idx" ON "app"."checkout_attempt_v2" ("owner_id", "capability_expires_at");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."order_v2" TO "qr_runtime";

GRANT SELECT, INSERT ON TABLE "app"."order_v2_line" TO "qr_runtime";

GRANT SELECT, INSERT, UPDATE ON TABLE "app"."order_comment_v2" TO "qr_runtime";

GRANT SELECT, INSERT ON TABLE "app"."order_local_outcome_v2" TO "qr_runtime";

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."checkout_attempt_v2" TO "qr_runtime";

GRANT SELECT, INSERT ON TABLE "app"."payment_link_v2_single_use_settlement" TO "qr_runtime";
