-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."password_reset_token" (
  "id" UUID NOT NULL,
  "user_id" UUID NOT NULL,
  "token_digest" VARCHAR(64) NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "consumed_at" TIMESTAMPTZ
);

ALTER TABLE "app"."password_reset_token" ADD CONSTRAINT "password_reset_token_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."password_reset_token" ADD CONSTRAINT "password_reset_token_token_digest_key" UNIQUE ("token_digest");

ALTER TABLE "app"."password_reset_token" ADD CONSTRAINT "password_reset_token_user_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "password_reset_token_user_created_at_idx" ON "app"."password_reset_token" ("user_id", "created_at");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."password_reset_token" TO "qr_runtime";
