-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."media_object" (
  "id" UUID NOT NULL,
  "identifier" VARCHAR(43) NOT NULL,
  "storage_key" VARCHAR(43) NOT NULL,
  "owner_id" UUID NOT NULL,
  "purpose" VARCHAR(15) NOT NULL,
  "state" VARCHAR(9) NOT NULL,
  "lifecycle_revision" BIGINT NOT NULL,
  "mime_type" VARCHAR(10) NOT NULL,
  "byte_size" BIGINT NOT NULL,
  "width" INTEGER NOT NULL,
  "height" INTEGER NOT NULL,
  "sha256" VARCHAR(64) NOT NULL,
  "purge_after" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_identifier_key" UNIQUE ("identifier");

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_storage_key_key" UNIQUE ("storage_key");

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_owner_fkey" FOREIGN KEY ("owner_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_purpose_closed" CHECK ("purpose" IN ('STOREFRONT_LOGO', 'PRODUCT_IMAGE'));

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_state_closed" CHECK ("state" IN ('WRITING', 'STAGED', 'ACTIVE', 'ORPHANED', 'DELETING'));

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_revision_nonnegative" CHECK ("lifecycle_revision" >= 0);

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_canonical_limits" CHECK (("mime_type" = 'image/webp') AND ("byte_size" > 0) AND ("byte_size" <= 5242880) AND ("width" > 0) AND ("width" <= 4096) AND ("height" > 0) AND ("height" <= 4096));

ALTER TABLE "app"."media_object" ADD CONSTRAINT "media_object_purge_consistent" CHECK ((("state" IN ('ORPHANED', 'DELETING')) AND ("purge_after" IS NOT NULL)) OR ((NOT ("state" IN ('ORPHANED', 'DELETING'))) AND ("purge_after" IS NULL)));

CREATE INDEX "media_object_owner_purpose_state_idx" ON "app"."media_object" ("owner_id", "purpose", "state");

CREATE INDEX "media_object_state_purge_after_idx" ON "app"."media_object" ("state", "purge_after");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."media_object" TO "qr_runtime";
