-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."supported_exchange_currency" (
  "code" VARCHAR(3) NOT NULL,
  "pair_id" UUID NOT NULL
);

ALTER TABLE "app"."supported_exchange_currency" ADD CONSTRAINT "supported_exchange_currency_pkey" PRIMARY KEY ("code");

ALTER TABLE "app"."supported_exchange_currency" ADD CONSTRAINT "supported_exchange_currency_pair_id_key" UNIQUE ("pair_id");

ALTER TABLE "app"."supported_exchange_currency" ADD CONSTRAINT "supported_exchange_currency_pair_fkey" FOREIGN KEY ("pair_id") REFERENCES "app"."catalog_currency_pair" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."supported_exchange_currency" ADD CONSTRAINT "supported_exchange_currency_code_bounds" CHECK (("code" >= 'AAA') AND ("code" <= 'ZZZ'));

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."supported_exchange_currency" TO "qr_runtime";

REVOKE DELETE ON TABLE "app"."catalog_currency_pair" FROM "qr_runtime";
