-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

ALTER TABLE "app"."user" ADD COLUMN "deleted_at" TIMESTAMPTZ;

CREATE TABLE "app"."user_deletion" (
  "id" UUID NOT NULL,
  "user_id" UUID NOT NULL,
  "actor_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."user_deletion" ADD CONSTRAINT "user_deletion_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."user_deletion" ADD CONSTRAINT "user_deletion_user_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

GRANT SELECT, INSERT ON TABLE "app"."user_deletion" TO "qr_runtime";
