-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."product_category" (
  "id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "name_pt_br" VARCHAR(160) NOT NULL,
  "name_en" VARCHAR(160) NOT NULL,
  "active" BOOLEAN NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."product_category" ADD CONSTRAINT "product_category_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."product_category" ADD CONSTRAINT "product_category_id_owner_id_key" UNIQUE ("id", "owner_id");

ALTER TABLE "app"."product_category" ADD CONSTRAINT "product_category_owner_name_pt_br_key" UNIQUE ("owner_id", "name_pt_br");

ALTER TABLE "app"."product_category" ADD CONSTRAINT "product_category_owner_name_en_key" UNIQUE ("owner_id", "name_en");

ALTER TABLE "app"."product_category" ADD CONSTRAINT "product_category_owner_fkey" FOREIGN KEY ("owner_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."product_category" ADD CONSTRAINT "product_category_version_nonnegative" CHECK ("version" >= 0);

CREATE INDEX "product_category_owner_active_name_idx" ON "app"."product_category" ("owner_id", "active", "name_pt_br", "id");

ALTER TABLE "app"."product" ADD COLUMN "category_id" UUID;

ALTER TABLE "app"."product" ADD CONSTRAINT "product_category_owner_fkey" FOREIGN KEY ("category_id", "owner_id") REFERENCES "app"."product_category" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "product_owner_category_id_idx" ON "app"."product" ("owner_id", "category_id", "id");

GRANT SELECT, INSERT, UPDATE ON TABLE "app"."product_category" TO "qr_runtime";

REVOKE DELETE ON TABLE "app"."product_category" FROM "qr_runtime";
