-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

ALTER TABLE "app"."user" ADD COLUMN "storefront_theme_id" VARCHAR(24);

ALTER TABLE "app"."user" ADD COLUMN "storefront_layout" VARCHAR(8);

ALTER TABLE "app"."user" ADD COLUMN "storefront_logo_media_identifier" VARCHAR(43);

ALTER TABLE "app"."user" ADD COLUMN "storefront_standalone_payments_enabled" BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE "app"."user" ADD COLUMN "storefront_default_currency_code" VARCHAR(3);

ALTER TABLE "app"."user" ADD CONSTRAINT "user_storefront_theme_id_closed" CHECK ("storefront_theme_id" IN ('pix-paper', 'cashier-daylight', 'settlement-sand', 'midnight-clearing', 'vault-blue', 'terminal-amber'));

ALTER TABLE "app"."user" ADD CONSTRAINT "user_storefront_layout_closed" CHECK ("storefront_layout" IN ('boxed', 'table'));

ALTER TABLE "app"."user" ADD CONSTRAINT "user_storefront_default_currency_code_bounds" CHECK (("storefront_default_currency_code" >= 'AAA') AND ("storefront_default_currency_code" <= 'ZZZ'));
