-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE INDEX "order_v2_state_settled_at_idx" ON "app"."order_v2" ("state", "settled_at");

CREATE INDEX "order_v2_created_at_idx" ON "app"."order_v2" ("created_at");

CREATE INDEX "order_local_outcome_v2_outcome_created_at_idx" ON "app"."order_local_outcome_v2" ("outcome", "created_at");

CREATE INDEX "checkout_attempt_v2_created_at_idx" ON "app"."checkout_attempt_v2" ("created_at");

CREATE INDEX "standalone_checkout_attempt_created_at_idx" ON "app"."standalone_checkout_attempt" ("created_at");
