-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."currency_pair_verification" (
  "owner_id" UUID NOT NULL,
  "pair_id" UUID NOT NULL,
  "quote_checked_at" TIMESTAMPTZ,
  "quote_outcome" VARCHAR(40),
  "observed_payment_method" VARCHAR(32),
  "observed_currency_symbol" VARCHAR(16),
  "observed_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."currency_pair_verification" ADD CONSTRAINT "currency_pair_verification_pkey" PRIMARY KEY ("owner_id", "pair_id");

ALTER TABLE "app"."currency_pair_verification" ADD CONSTRAINT "currency_pair_verification_owner_fkey" FOREIGN KEY ("owner_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."currency_pair_verification" ADD CONSTRAINT "currency_pair_verification_pair_fkey" FOREIGN KEY ("pair_id") REFERENCES "app"."catalog_currency_pair" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "currency_pair_verification_pair_idx" ON "app"."currency_pair_verification" ("pair_id");

GRANT SELECT, INSERT, UPDATE ON TABLE "app"."currency_pair_verification" TO "qr_runtime";

ALTER TABLE "app"."provider_order" ADD COLUMN "currency_symbol" VARCHAR(16);
