-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."payment_link_v2" (
  "id" UUID NOT NULL,
  "identifier" VARCHAR(24) NOT NULL,
  "owner_id" UUID NOT NULL,
  "composition_kind" VARCHAR(13) NOT NULL,
  "description_pt_br" VARCHAR(160),
  "description_en" VARCHAR(160),
  "amount" TEXT,
  "currency_pair_id" UUID NOT NULL,
  "link_type" VARCHAR(10) NOT NULL,
  "expires_at" TIMESTAMPTZ,
  "active" BOOLEAN NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "app"."payment_link_v2_line" (
  "payment_link_v2_id" UUID NOT NULL,
  "owner_id" UUID NOT NULL,
  "product_id" UUID NOT NULL,
  "position" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL
);

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_identifier_key" UNIQUE ("identifier");

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_id_owner_id_key" UNIQUE ("id", "owner_id");

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_owner_fkey" FOREIGN KEY ("owner_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_currency_pair_fkey" FOREIGN KEY ("currency_pair_id") REFERENCES "app"."catalog_currency_pair" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_composition_kind_closed" CHECK ("composition_kind" IN ('PRODUCT_LINES', 'FIXED_AMOUNT'));

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_composition_complete" CHECK ((("composition_kind" = 'FIXED_AMOUNT') AND ("description_pt_br" IS NOT NULL) AND ("description_en" IS NOT NULL) AND ("amount" IS NOT NULL)) OR (("composition_kind" = 'PRODUCT_LINES') AND ("description_pt_br" IS NULL) AND ("description_en" IS NULL) AND ("amount" IS NULL)));

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_link_type_closed" CHECK ("link_type" IN ('SINGLE_USE', 'REUSABLE'));

ALTER TABLE "app"."payment_link_v2" ADD CONSTRAINT "payment_link_v2_version_nonnegative" CHECK ("version" >= 0);

ALTER TABLE "app"."payment_link_v2_line" ADD CONSTRAINT "payment_link_v2_line_pkey" PRIMARY KEY ("payment_link_v2_id", "position");

ALTER TABLE "app"."payment_link_v2_line" ADD CONSTRAINT "payment_link_v2_line_link_product_key" UNIQUE ("payment_link_v2_id", "product_id");

ALTER TABLE "app"."payment_link_v2_line" ADD CONSTRAINT "payment_link_v2_line_link_owner_fkey" FOREIGN KEY ("payment_link_v2_id", "owner_id") REFERENCES "app"."payment_link_v2" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."payment_link_v2_line" ADD CONSTRAINT "payment_link_v2_line_product_owner_fkey" FOREIGN KEY ("product_id", "owner_id") REFERENCES "app"."product" ("id", "owner_id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "app"."payment_link_v2_line" ADD CONSTRAINT "payment_link_v2_line_position_bounds" CHECK (("position" >= 1) AND ("position" <= 20));

ALTER TABLE "app"."payment_link_v2_line" ADD CONSTRAINT "payment_link_v2_line_quantity_bounds" CHECK (("quantity" >= 1) AND ("quantity" <= 9999));

CREATE INDEX "payment_link_v2_owner_created_at_id_idx" ON "app"."payment_link_v2" ("owner_id", "created_at", "id");

CREATE INDEX "payment_link_v2_owner_active_created_at_id_idx" ON "app"."payment_link_v2" ("owner_id", "active", "created_at", "id");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."payment_link_v2" TO "qr_runtime";

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app"."payment_link_v2_line" TO "qr_runtime";
