-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

CREATE TABLE "app"."password_reset_request" (
  "id" UUID NOT NULL,
  "user_id" UUID NOT NULL,
  "actor_id" UUID NOT NULL,
  "outcome" VARCHAR(16) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "app"."password_reset_request" ADD CONSTRAINT "password_reset_request_pkey" PRIMARY KEY ("id");

ALTER TABLE "app"."password_reset_request" ADD CONSTRAINT "password_reset_request_user_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

GRANT SELECT, INSERT ON TABLE "app"."password_reset_request" TO "qr_runtime";
