-- CreateTable
CREATE TABLE "app"."_database_foundation_fixture" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "key" VARCHAR(64) NOT NULL,
    "quantity" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "_database_foundation_fixture_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "database_foundation_fixture_key_key" UNIQUE ("key"),
    CONSTRAINT "database_foundation_fixture_key_nonblank" CHECK (length(btrim("key")) > 0),
    CONSTRAINT "database_foundation_fixture_quantity_nonnegative" CHECK ("quantity" >= 0)
);

-- Runtime access to application objects is supplied by qr_migrator-scoped
-- default privileges. Migration metadata is always explicitly excluded.
DO $migration$
BEGIN
    IF to_regclass('app._prisma_migrations') IS NOT NULL THEN
        REVOKE ALL PRIVILEGES ON TABLE app."_prisma_migrations" FROM qr_runtime;
    END IF;
END
$migration$;
