-- Generated by pop/scripts/migration-policy.mjs. Do not edit.

ALTER TABLE "app"."product" ADD COLUMN "currency_code" VARCHAR(3);

ALTER TABLE "app"."product" ADD COLUMN "image_media_id" VARCHAR(43);

ALTER TABLE "app"."product" ADD COLUMN "archived_at" TIMESTAMPTZ;

ALTER TABLE "app"."product" ADD CONSTRAINT "product_currency_code_bounds" CHECK (("currency_code" >= 'AAA') AND ("currency_code" <= 'ZZZ'));
